# Generated by Django 3.2.7 on 2021-11-26 15:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ecommers', '0002_auto_20211126_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
