# Generated by Django 3.2.6 on 2021-12-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommers', '0007_auto_20211225_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbooking',
            name='booking_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
