# Generated by Django 3.2.6 on 2021-12-26 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommers', '0008_productbooking_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category-img/'),
        ),
    ]
