# Generated by Django 3.2.6 on 2021-12-26 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommers', '0009_alter_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_image4',
            field=models.ImageField(blank=True, null=True, upload_to='productImages/'),
        ),
    ]
