# Generated by Django 3.2.6 on 2021-12-29 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommers', '0011_cart_booked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='images',
            new_name='image',
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='pincode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
