# Generated by Django 3.2.6 on 2022-01-01 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommers', '0013_cart_total_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productbooking',
            name='product',
        ),
        migrations.AddField(
            model_name='productbooking',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productbooking',
            name='cart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ecommers.cart'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productbooking',
            name='city',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='productbooking',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productbooking',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='productbooking',
            name='name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='productbooking',
            name='number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productbooking',
            name='pincode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productbooking',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
