# Generated by Django 3.2.6 on 2022-01-05 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommers', '0016_auto_20220104_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbooking',
            name='payment_type',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='productbooking',
            name='cart',
            field=models.ManyToManyField(blank=True, to='ecommers.Cart'),
        ),
    ]
