# Generated by Django 3.2.6 on 2022-01-05 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommers', '0017_auto_20220105_2313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productbooking',
            old_name='total_ammount',
            new_name='total_amount',
        ),
    ]
