# Generated by Django 3.2.6 on 2022-01-07 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommers', '0018_rename_total_ammount_productbooking_total_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(blank=True, max_length=1000, null=True)),
                ('product_id', models.CharField(blank=True, max_length=50000, null=True)),
                ('defect_info', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommers.customer')),
            ],
        ),
    ]
