# Generated by Django 3.2.6 on 2022-01-07 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommers', '0019_productrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrequest',
            name='request_action',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
