# Generated by Django 3.2.6 on 2022-01-07 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommers', '0020_productrequest_request_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrequest',
            name='accept_message',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='productrequest',
            name='return_payment',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
