# Generated by Django 3.2.6 on 2022-01-07 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommers', '0022_productrequest_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productrequest',
            old_name='customer',
            new_name='customer_id',
        ),
    ]
